### ISSUE TITLE
Duplicate thresholds created

### ISSUE THREAD

**Issue by DigitalPackrat** [Cacti/plugin_thold#138]
Creating thresholds using device templates is generating duplicate thresholds on most of the threshold names. What I found is if multiple threshold templates contain the same DS Name this occurs.

For instance using a copy of my 8.8h install upgraded to 1.1.28 as starting point. I dropped all the thold tables and installed thold 1.0.3 and duplicated the issue in 1.0.4. Three of the data templates have duplicate data source names. Creating a thold template for any one of these, assigning it to a device template and applying tholds to a device works as expected.
Creating a thold template for 2 or 3 of these data template with duplicate data source names generates multiple tholds for each one.

Ie. data templates for fan speed, thermal sensor and voltage. All had the samd DS name sensorReading.
Create tholds for a combination of 2 or 3 results in 2-3x tholds generated. So fan 1 would appear 3 times, one with a low value trigger for the fan, the other two times would be limits for thermal sensor and voltage. The same triplicate would happen to thermal sensor 1 and voltage 1.

Changing the DS name did not help till the thold template was deleted and re added. Thold .5 was able to handle this situation. I only have a few duplicates but a fix would be helpful for anyone attempting an upgrade on a larger system.

**Comment by netniV** [comment]
This may be down to the creation of multiple graphs? In cacti 1.1.28, I ended up with some graphs duplicating which in turn could create multiple thold graphs.  Have you checked for graph duplicates?

**Comment by DigitalPackrat** [comment]
There are no duplicate graphs. This is only happens when tholds are created for more than one data template that have the same DS name.

**Comment by DigitalPackrat** [comment]
This is actually a bigger issue than I expected. Changing the datasource name causes issues with existing RRD's. So that doesn't work as a workaround for this glitch is thold.

**Comment by DigitalPackrat** [comment]
Been experimenting with this but still at a standstill. 

Changing the DS name allows the tholds to be created without duplicates but the DS name no longer matches the RRD so no update can be performed.

Changing the DS name back to the original after tholds are created allows RRD's to be updated but breaks if more than one of the three tholds with the same DS name are enabled. Basically it appears to be working then after 30 minutes RRD's stop updating. At that point I can disable all tholds and RRD's start updating again. If I delete tholds for any two of the three with duplicate DS names RRD's and tholds work.

So I am stuck at thold not working with data sources that have the same internal data source name. I also did a clean install on a test system with Cacti 1.1.29 and PHP 7.0.26 with no change. Previous install was 1.1.28 and PHP 5.6.9.

**Comment by netniV** [comment]
Are you seeing any errors in the cacti.log whilst this is going on?  I can't think why a threshold would stop graphing, unless there's some sort of error occurring.

**Comment by DigitalPackrat** [comment]
Yes, there are two errors that come up when thold is enabled and more than one internal DS name is being monitored. 
The first is PHP Maximum execution time exceeded in database.php on line 165
Immediately after that there is a backtrace cactishutdownhandler in functions.php 4446 cacti_defub_backtrace.

Unfortunately some company security policies will not allow me to post full logs which may make this difficult.

**Comment by netniV** [comment]
I understand that.  Could you post a copy of that backtrace and a few lines before that?  This will help identify where the issue could be.  Out of curiosity, how many hosts do you have? how many thresholds?  

### _Senstive Data_
You can replace any sensitive data with alternative text (but be consistent), eg, if host1.mydomain.local replace with mytext123 in all places.  If it's IP addresses for example, change 192.168.1.1 to x.x.x.a, 192.168.1.2 to x.x.x.b, 10.1.1.1 to x.x.x.c 

Most data in the cacti.log would be standard information with the exception of maybe host, url and physical path location. Replace any url with "https://<cactiserver>/" and path with "/<cacti>/" 

Just try to be consistent with the name mapping you do so that when looking at the logs, we can see its the same host/ip across the different lines.

For example, with different hosts my cacti log would be changed before pasting here to be:
```
2018/01/02 16:36:48 - CMDPHP WARNING: SNMP Error:'Timeout (1000 ms)', Device:’x.x.x.a’, OID:'.1.3.6.1.2.1.1.2.0'
2018/01/02 22:00:10 - CMDPHP WARNING: SNMP Error:'snmp2_get(): No response from x.x.x.b’, Device:’x.x.x.b’, OID:'.1.3.6.1.2.1.25.2.3.1.6.1'
2018/01/02 22:13:09 - CMDPHP WARNING: SNMP Error:'snmp2_get(): No response from x.x.x.b’, Device:’x.x.x.b’, OID:'.1.3.6.1.2.1.25.2.3.1.6.1'
2018/01/03 06:04:09 - CMDPHP WARNING: SNMP Error:'snmp2_get(): No response from x.x.x.c’, Device:’x.x.x.c’, OID:'.1.3.6.1.2.1.25.2.3.1.6.1'
2018/01/03 06:07:18 - PHPSVR WARNING: Script Server terminated with signal '15' in file:'ss_host_disk.php', function:'ss_host_disk', params:’’x.x.x.a’ '47' '2:161:3000:5:10:public::::::' 'get' 'total' '1''
2
```
But that allows us to see that the same host had a timeout and a script server error. If x.x.x.a and x.x.x.b are actually on completely different subnets I could have even used x.x.a.a and x.x.b.b to signify that though it often doesn't matter as long as we can see if the same host has issues.

**Comment by cigamit** [comment]
There is a hard relationship between the data source name in Cacti and the data source name in the RRDfile.  I recommend never changing something like this unless you have a non-production test system where you can restore from backup without loosing your job.

**Comment by cigamit** [comment]
Okay, this is likely being caused by the 'autocreate' function.  Though you can manually create multiple thresholds per local_data_id, you should likely avoid that when using autocreate().  Also, if you are using the same data template for multiple graph templates we down the same rabit hole.  This might take some time to fix.

**Comment by cigamit** [comment]
Okay, autocreate() does check and avoid that.  But maybe there is a logic flaw.

**Comment by cigamit** [comment]
I added more join expressions to reduce the likelihood of getting into situations where you can get duplicate tholds.  Please test the latest thold_functions.php and let us know if the issue is resolved.

**Comment by DigitalPackrat** [comment]
Thanks for the new thold_functions.php. Is there anything else that needs to be changed to make it work? I am seeing the same issue as before.

**Comment by DigitalPackrat** [comment]
May have spoken too soon. Fresh install of 1.1.36 on a test system using the database from 8.8h looks promising. Will update when I get a bit further.

**Comment by DigitalPackrat** [comment]
I think this is fixed. I have a few thousand thresholds setup so far and can't find any duplicates.

This was with a fresh install of 1.1.36 using a database upgraded from 8.8h. Thold tables dropped then installed thold 1.0.4.

Thank you.
