### ISSUE TITLE
In foreach cycle, $alert_email can be concated with previous iteration

### ISSUE THREAD

**Issue by DileSoft** [Cacti/plugin_thold#220]
https://github.com/Cacti/plugin_thold/blob/88a13e2c68ca216c6c26a660b08352953fe3fab7/includes/polling.php#L642

**Comment by netniV** [comment]
The logic isn't totally correct there but it is more because of the other entries.  If the thresholds being examined do not all confirm to the same mode, the $alert_email field could be cleared incorrectly.

$alert_email is normally primed with the Global email settings first.  If a threshold is using both global and device lists, then it would append the device list to the global which is what the above line is doing.

However, if another threshold was hit and that one only used a device list, it would clear out the existing data and there would be no global list going forward even if something wanted to use it.

There should be a separate variable holding the global list on a constant basis which is used to prime the $alert_email when the global list is set to be used.  The whole logic needs a review which is scheduled to be done once the 1.2 release has been finialised.

**Comment by DileSoft** [comment]
It really big bug for me where a lot of hosts down. I got many wrong emails. Look at my pull request (I used this patch on my server): https://github.com/Cacti/plugin_thold/pull/221

**Comment by netniV** [comment]
I think that patch should be OK.  Please update the change log as noted on my review.

**Comment by netniV** [comment]
This was merged into the development branch.
