### ISSUE TITLE
requires cacti 1.2.1

### ISSUE THREAD

**Issue by chathurag** [Cacti/plugin_thold#235]
Unable to install this plugin on cacti 1.2.0 as it requires 1.2.1
but cacti 1.2.1 is not officialy released

**Comment by netniV** [comment]
You can download the latest release from the releases tab of the code section. That will be 1.2.0 compatible.  If you have downloaded directly from develop, this is going to require 1.2.1 because it depends on functionality that only exists in the develop branch on the core repo.  

1.2.1 will likely be released (in the next week) before a full thold release is made so this is technically not an issue.
