### ISSUE TITLE
Minor issue:  Thold http files should not output by page_head hook for other non-thold plugins pages

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_thold#263]
Prefer diff like below

```diff
--- ./setup.php 2019-02-13 21:38:49.000000000 +0800
+++ ./setup.php 2019-03-04 14:37:22.861432341 +0800
@@ -1111,6 +1111,8 @@
 function thold_page_head() {
        global $config;

+       if(strstr($_SERVER['SCRIPT_NAME'], 'plugins' . DIRECTORY_SEPARATOR . 'thold' . DIRECTORY_SEPARATOR) === false)
+               return;
        if (file_exists($config['base_path'] . '/plugins/thold/themes/' . get_selected_theme() . '/main.css')) {
                print "<link href='" . $config['url_path'] . 'plugins/thold/themes/' . get_selected_theme() . "/main.css' type='text/css' rel='stylesheet'>\n";
        }

**Comment by netniV** [comment]
Sounds reasonable, have you prepared a pull request with this is (and updated the change log in README.md) ?

It may not get accepted though because I know that another plugin monitor, for example has CSS that must be loaded on a full page load otherwise it's not present for the AJAX calls within constantly reincluding it.

**Comment by ddb4github** [comment]
Actually, I think that current AJAX loading architecture might provide a  option to forcefully reload whole page cross plugin, or for some menu/tab items.  Like tag '"EXTERNAL'

**Comment by netniV** [comment]
Well, I have plans for that in 1.3.  I had hoped to have it in 1.2 but it needed more testing time than we had.

**Comment by TheWitness** [comment]
I'm not a big fan of inline CSS, and we use it quite sparingly in Cacti.  If the CSS for thold conflicts with the CSS from the core Cacti, that should be the real issue here.  Right now, we first have to identify what is interfering, and possibly fix that issue in thold as I don't want to really blow up the performance advancements we have made by only loading the <head> once.

**Comment by TheWitness** [comment]
So, closing this issue as it's important to remember we only load the CSS once for all pages, so, people have to pay attention to conflicting CSS.
