### ISSUE TITLE
Threshold Daemon Server (get rid of start script)

### ISSUE THREAD

**Issue by fskale** [Cacti/plugin_thold#381]
Change the threshold deaemon service to forking and get rid of the uneeded thold_daemon script.
Since systemd has the ability to track forked processes and stop it accordingly, there's no need to fork a subscript which stops the acutual daemon.
Also it should be pointed out, that it must be started after mysql/mariadb so you should take care of dependend services !
my implementation is as follows:
<pre>
[Unit]
Description=Cacti Threshold Daemon Service
After=network.target auditd.service mariadb.service php7.0-fpm.service nginx.service

[Service]
Type=forking
ExecStart=/usr/bin/php -q /usr/share/cacti/site/plugins/thold/thold_daemon.php
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
</pre>
Please do not hesitate to contact me if you have any further questions regarding the issue !

Rgds.
Franz

**Comment by netniV** [comment]
Whilst we can provide the templates for this to work, installation is system dependant since there are still non-systemd variants out there.  The idea of forking isn't a bad one for child processes but that depends if pcntl is enabled within PHP.

https://www.php.net/manual/en/function.pcntl-fork.php

Something to mull over but overall a good suggestion :)

**Comment by fskale** [comment]
To get the threshold deamon to fork, you have to enable pcntl* functions.
When using debian as distribution, you have to enable pcntl* anyhow.
You should provide a hint in the README to enable pcntl* functions in the php.ini as well as a systemd unit and a systemV init script though.

**Comment by fskale** [comment]
Forgot to mention that it should be outlined to run the service as user not as root.
Default for most installations it's 'www-data'.
For completeness, my unit file:
<pre>
[Unit]
Description=Cacti Threshold Daemon Service
After=network.target auditd.service mariadb.service php7.0-fpm.service nginx.service

[Service]
Type=forking
User=cacti
Group=cacti
ExecStart=/usr/bin/php -q /usr/share/cacti/site/plugins/thold/thold_daemon.php
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
</pre>

**Comment by bmfmancini** [comment]
So I am running on a rhel7 system and I am able to get the thold daemon running but it stops thold from running when I setup thold to use the daemon 

this is my config


[Unit]
Description=Cacti Threshold Daemon Service

[Service]
Type=oneshot
ExecStart=/var/www/html/cacti/plugins/thold/service/systemd/thold_daemon
ExecStop=/var/www/html/cacti/plugins/thold/service/systemd/thold_daemon
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target

so with the default instructions, this would run as root 
are you saying that this should be run as the cacti user instead?

if so we should fix the documentation 
@netniV  can you confirm this ?
I will also try this to see if it fixed my issue as well

**Comment by bmfmancini** [comment]
When I used those settings same result the daemon comes up but does not proccess tholds

SYSTEM THOLD DAEMON STATS: **TotalTime:0.000 MaxRuntime:0.000 Processed:0 InProcess:12448** TotalDevices:1009 DownDevices:21 NewDownDevices:1 MaxProcesses:4 Completed:0 Running:0 Broken:0 

Type=oneshot
ExecStart=/var/www/html/cacti/plugins/thold/service/systemd/thold_daemon
ExecStop=/var/www/html/cacti/plugins/thold/service/systemd/thold_daemon
RemainAfterExit=yes
User=apache
Group=apache

[Install]
WantedBy=multi-user.target

**Comment by fskale** [comment]
@bmfmancini 
My testsetup is running for weeks w/o any problems so far.
As i mentioned, a changed the systemd unit as well as using nginx as webserver along with fpm.
The socket uid/gid is www-data which then switches to the cacti user for security reasons.
<pre>
cacti     24716  0.0  0.1 299572 16164 ?        S    Oct03   8:10 /usr/bin/php -q /usr/share/cacti/site/plugins/thold/thold_daemon.php
</pre>
And the units status:
<pre>
systemctl  status thold_daemon.service
● thold_daemon.service - Cacti Threshold Daemon Service
   Loaded: loaded (/lib/systemd/system/thold_daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-10-03 13:50:15 CEST; 1 weeks 6 days ago
 Main PID: 24716 (php)
    Tasks: 1 (limit: 9516)
   CGroup: /system.slice/thold_daemon.service
           └─24716 /usr/bin/php -q /usr/share/cacti/site/plugins/thold/thold_daemon.php

Oct 03 13:50:15 cacti-1 systemd[1]: Starting Cacti Threshold Daemon Service...
Oct 03 13:50:15 cacti-1 php[24712]: Starting Thold Daemon ... [OK]
Oct 03 13:50:15 cacti-1 systemd[1]: Started Cacti Threshold Daemon Service.
</pre>

**Comment by bmfmancini** [comment]
This is what I have 

systemctl status thold_daemon.service -l
● thold_daemon.service - Cacti Threshold Daemon Service
   Loaded: loaded (/etc/systemd/system/thold_daemon.service; disabled; vendor preset: disabled)
   Active: active (exited) since Wed 2019-10-16 16:12:21 EDT; 28min ago
  Process: 3780 ExecStart=/usr/bin/php /var/www/html/cacti/plugins/thold/service/systemd/thold_daemon -f (code=exited, status=0/SUCCESS)
 Main PID: 3780 (code=exited, status=0/SUCCESS)

Oct 16 16:12:22 cacti-ebu-esa php[3780]: path_thold=/var/www/html/cacti/plugins/thold
Oct 16 16:12:22 cacti-ebu-esa php[3780]: start() {
Oct 16 16:12:22 cacti-ebu-esa php[3780]: exec php -q ${path_thold}/thold_daemon.php
Oct 16 16:12:22 cacti-ebu-esa php[3780]: }
Oct 16 16:12:22 cacti-ebu-esa php[3780]: stop() {
Oct 16 16:12:22 cacti-ebu-esa php[3780]: exec kill `pgrep -a php | grep thold_daemon.php | awk '{print $1}'`
Oct 16 16:12:22 cacti-ebu-esa php[3780]: }
Oct 16 16:12:22 cacti-ebu-esa php[3780]: case $1 in
Oct 16 16:12:22 cacti-ebu-esa php[3780]: start|stop) "$1" ;;
Oct 16 16:12:22 cacti-ebu-esa php[3780]: esac

**Comment by bmfmancini** [comment]
systemctl status thold_daemon.service -l
● thold_daemon.service - Cacti Threshold Daemon Service
   Loaded: loaded (/etc/systemd/system/thold_daemon.service; disabled; vendor preset: disabled)
   Active: active (exited) since Wed 2019-10-16 16:12:21 EDT; 28min ago
  Process: 3780 ExecStart=/usr/bin/php /var/www/html/cacti/plugins/thold/service/systemd/thold_daemon -f (code=exited, status=0/SUCCESS)
 Main PID: 3780 (code=exited, status=0/SUCCESS)

Oct 16 16:12:22 hostname php[3780]: path_thold=/var/www/html/cacti/plugins/thold
Oct 16 16:12:22 hostname php[3780]: start() {
Oct 16 16:12:22 hostname php[3780]: exec php -q ${path_thold}/thold_daemon.php
Oct 16 16:12:22 hostname php[3780]: }
Oct 16 16:12:22 hostname php[3780]: stop() {
Oct 16 16:12:22 hostname php[3780]: exec kill `pgrep -a php | grep thold_daemon.php | awk '{print $1}'`
Oct 16 16:12:22 hostname php[3780]: }
Oct 16 16:12:22 hostname php[3780]: case $1 in
Oct 16 16:12:22 hostname php[3780]: start|stop) "$1" ;;
Oct 16 16:12:22 hostname php[3780]: esac

**Comment by netniV** [comment]
> To get the threshold deamon to fork, you have to enable pcntl* functions.
> When using debian as distribution, you have to enable pcntl* anyhow.
> You should provide a hint in the README to enable pcntl* functions in the php.ini as well as a systemd unit and a systemV init script though.

Have you ensured you have those functions enabled @bmfmancini ?  Also, since you are on CentOS 7, check whether you have any SELinux issues kicking in.

**Comment by TheWitness** [comment]
Yea, you have to use the forking type for this to be happy I think.  This is resolved now.
