### ISSUE TITLE
Thold not sending emails(api_plugin_hook MAILER ERROR)

### ISSUE THREAD

**Issue by rtripon** [Cacti/plugin_thold#388]
Hello,
I've noticed that THOLD is not sending anymore(I dont know exactly when it stopped sending, was working when sistem was install). Probably after one git pull, but cant say for sure.
THOLD version : 1.3.2
Cacti  Version 1.3.0 - Dev 79f29cd @ 2019-09-28
I have a thredshold created for up/down interfaces, I see that is TRIGGERED in THOLD tab, but no emails at all.

2019/11/03 20:15:32 - CMDPHP MAILER ERROR:
2019/11/03 20:15:32 - CMDPHP MAILER ERROR Backtrace:  (/poller.php[796]:api_plugin_hook(), /lib/plugins.php[74]:api_plugin_run_plugin_hook(), /lib/plugins.php[177]:thold_poller_bottom(), /plugins/thold/includes/polling.php[45]:thold_check_all_thresholds(), /plugins/thold/includes/polling.php[473]:thold_check_threshold(), /plugins/thold/thold_functions.php[2208]:thold_mail(), /plugins/thold/thold_functions.php[5355]:mailer(), /lib/functions.php[3489]:record_mailer_error(), /lib/functions.php[3687]:cacti_debug_backtrace())

**Comment by DoubleBeast** [comment]
Hello everyone, i have the same issue but with different error message:


13-11-2019 23:12:38 - THOLD ERROR: Sending Email Failed.  Error was Invalid address:  (From): Cacti@localhost
--
13-11-2019 23:12:38 - CMDPHP MAILER ERROR Backtrace:   (C:\Apache24\htdocs\cacti\poller.php[796]:api_plugin_hook(),  C:\Apache24\htdocs\cacti\lib\plugins.php[74]:api_plugin_run_plugin_hook(),  C:\Apache24\htdocs\cacti\lib\plugins.php[177]:thold_poller_bottom(),  C:\Apache24\htdocs\cacti\plugins\thold\includes\polling.php[45]:thold_check_all_thresholds(),   C:\Apache24\htdocs\cacti\plugins\thold\includes\polling.php[469]:thold_check_threshold(),   C:\Apache24\htdocs\cacti\plugins\thold\thold_functions.php[2202]:thold_mail(),   C:\Apache24\htdocs\cacti\plugins\thold\thold_functions.php[5344]:mailer(),  C:\Apache24\htdocs\cacti\lib\functions.php[3475]:record_mailer_error(),   C:\Apache24\htdocs\cacti\lib\functions.php[3681]:cacti_debug_backtrace())
13-11-2019 23:12:38 - CMDPHP MAILER ERROR: Invalid address:  (From): Cacti@localhost

aparently the mail is not send because of the invalid address, i check the main mail config and the thold config and the address is ok, i suposse that somewhere into the thold database it is not changed for some reason. By the way the test email from main config are working fine.

**Comment by netniV** [comment]
Basically, that is PHP Mailer telling us that the email address is not a valid email address (which it technically isn't).  This isn't a bug but a problem with the email address used to send from.

**Comment by DoubleBeast** [comment]
> 
> 
> Basically, that is PHP Mailer telling us that the email address is not a valid email address (which it technically isn't). This isn't a bug but a problem with the email address used to send from.

indeed that is the meaning of the error but the real question is why thold use that email if cacti is configured with a valid email?

**Comment by DoubleBeast** [comment]
I modified the line 5262 of the file "thold_functions.php" an change the "Cacti@localhost" value to a valid email and now thold send emails in some ocations, when the mail is not send the following error shows into the log:

21-11-2019  16:11:43 - CMDPHP MAILER ERROR Backtrace:   (C:\Apache24\htdocs\cacti\poller.php[796]:api_plugin_hook(),  C:\Apache24\htdocs\cacti\lib\plugins.php[74]:api_plugin_run_plugin_hook(),  C:\Apache24\htdocs\cacti\lib\plugins.php[177]:thold_poller_bottom(),  C:\Apache24\htdocs\cacti\plugins\thold\includes\polling.php[45]:thold_check_all_thresholds(),   C:\Apache24\htdocs\cacti\plugins\thold\includes\polling.php[469]:thold_check_threshold(),   C:\Apache24\htdocs\cacti\plugins\thold\thold_functions.php[2202]:thold_mail(),   C:\Apache24\htdocs\cacti\plugins\thold\thold_functions.php[5344]:mailer(),  C:\Apache24\htdocs\cacti\lib\functions.php[3483]:record_mailer_error(),   C:\Apache24\htdocs\cacti\lib\functions.php[3681]:cacti_debug_backtrace())
--
21-11-2019 16:11:43 - CMDPHP MAILER ERROR:
