### ISSUE TITLE
361 Not Solved

### ISSUE THREAD

**Issue by nicolapiazzi** [Cacti/plugin_thold#397]
Latest thold develop and latest cacti at 30/12/2019

**Comment by nicolapiazzi** [comment]
![a1](https://user-images.githubusercontent.com/54310887/71579159-a4e74800-2afb-11ea-9303-0567f035beab.PNG)

**Comment by nicolapiazzi** [comment]
![a2](https://user-images.githubusercontent.com/54310887/71579183-b92b4500-2afb-11ea-9aff-b85e9433f434.PNG)

**Comment by nicolapiazzi** [comment]
You see that it transform 0.11 into 0.88

**Comment by nicolapiazzi** [comment]
![b1](https://user-images.githubusercontent.com/54310887/71579223-e677f300-2afb-11ea-870e-2a5b38334231.PNG)
apply a donothing cdef

**Comment by nicolapiazzi** [comment]
apply cdef to thold
![b2](https://user-images.githubusercontent.com/54310887/71579249-08717580-2afc-11ea-8179-d1c4a38bc11d.PNG)

**Comment by nicolapiazzi** [comment]
![a3](https://user-images.githubusercontent.com/54310887/71579255-13c4a100-2afc-11ea-8860-405727b564a1.PNG)
New thold have correctly 0.11 instead 0.88 but it divide by 8 current value

**Comment by TheWitness** [comment]
The issue here is that your graph is in bit/second, where the template is in BYTES/second.  So, if you enter 0.111, it'll be converted to 0.888.  Look at my example below.  The first one is in 'bit/second' and the second one is in 'bytes/second'.  They are both based off the same thold template.

![image](https://user-images.githubusercontent.com/1439914/75631425-c8dd0d80-5bc0-11ea-85a1-7150a6240210.png)

So, this is really not an issue as the display is always in the unit (or should be) of the Graph Template.
