### ISSUE TITLE
XSS Vulnerabilities if host/graph name include script

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_thold#430]
**Describe the bug**
Execute script like `alert('Local Linux Machine')` during create thold

**To Reproduce**
1. Go to Console->Devices
2. Click on 'Local Linux Machine'
3. Change `Description` to `<script>alert('Local Linux Machine');</script>` 
4. Click Save

***Case#1***

5. Go to Console->Thresholds
6. Edit any thold under changed Device
7. **See error**,  popup `alert('Local Linux Machine')`

***Case#2***

8. Add a new Threshold by top-right '+' button
10. Select `Non Templated`
11. Select modified device at step#3
12.  See error, first popup `alert('Local Linux Machine')` as below
![image](https://user-images.githubusercontent.com/17589018/81503201-e3480b80-9314-11ea-9ac0-24ee91122aa7.png)
13. Select a `Graph` which name include `<script>alert('Local Linux Machine');</script>`
14. See error, the second popup as above
15. Select a `Data Source`
16. See error, the third popup as above
17. Click 'Create'
16. See error, the four popup as above like Case#1->Step#7

**Comment by netniV** [comment]
This should have a CVE assigned to it, can you get one?

**Comment by yingbaiibm** [comment]
Append more cve issue
### **Case #3 notify_lists.php with popup exist**
1. add a notification
2. go to device page, popup exist due to there is device name as <script>alert(1);</script>
![82417104-a535af00-9aad-11ea-8ca5-8a1c14d3a703](https://user-images.githubusercontent.com/47589910/82517714-483f0500-9b50-11ea-8e26-8cb021625e90.png)

**Comment by netniV** [comment]
Thanks @yingbaiibm - these tests are gratefully received!
