### ISSUE TITLE
 THOLD ERROR: RPN Expression is invalid! -- the bug from 2017 is back! please help!

### ISSUE THREAD

**Issue by ikorzha** [Cacti/plugin_thold#495]
Cacti team I have just upgraded from thold 1.0.6 (where this bug was resolved by cigamit back in 2017).
https://github.com/Cacti/plugin_thold/issues/109
And now in 1.5.3 or even 1.3.0 this bug is back!
I really need help with it as I am getting thousands of error log messages per minute:
![image](https://user-images.githubusercontent.com/11211789/111855817-21cb3100-88fd-11eb-976e-d5b4d8fcf1ba.png)

Please help if possible...

**Comment by bmfmancini** [comment]
I also see this behaviour with the following RPN

|ds:traffic_in|,8,*,1000000,/,|query_ifHighSpeed|,/,100,*

The error happens on some specific ports and they come in every polling cycle 

```

2021-03-19  21:10:04 - THOLD ERROR: RPN Expression is invalid!  THold:'MANCINI-SW1-test - Traffic - StackSub-St1-2 [traffic_in]',  Value:'0', Expression:'\|ds:traffic_in\|,\|query_ifHighSpeed\|,/,0.0008,*',  Processed:'0,0,/,0.0008,*'
--
2021-03-19 21:10:04 - THOLD ERROR: RPN value: v2 "" is Not valid for operator "*". Stack:"0.0008"
2021-03-19 21:10:04 - THOLD ERROR: RPN Expression is invalid!  THold:'MANCINI-SW1-test - Traffic - StackSub-St1-1 [traffic_in]',  Value:'0', Expression:'\|ds:traffic_in\|,\|query_ifHighSpeed\|,/,0.0008,*',  Processed:'0,0,/,0.0008,*'
2021-03-19 21:10:04 - THOLD ERROR: RPN value: v2 "" is Not valid for operator "*". Stack:"0.0008"
2021-03-19 21:10:04 - THOLD ERROR: RPN Expression is invalid!  THold:'MANCINI-SW1-test - Traffic - StackPort1 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,\|query_ifHighSpeed\|,/,0.0008,*',  Processed:'0,0,/,0.0008,*'
2021-03-19 21:10:04 - THOLD ERROR: RPN value: v2 "" is Not valid for operator "*". Stack:"0.0008"
2021-03-19 21:10:03 - THOLD ERROR: RPN Expression is invalid!  THold:'MANCINI-SW1 - Traffic - StackSub-St1-2 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,\|query_ifHighSpeed\|,/,0.0008,*',  Processed:'0,0,/,0.0008,*'
2021-03-19 21:10:03 - THOLD ERROR: RPN value: v2 "" is Not valid for operator "*". Stack:"0.0008"
2021-03-19 21:10:03 - THOLD ERROR: RPN Expression is invalid!  THold:'MANCINI-SW1 - Traffic - StackSub-St1-1 [traffic_in]', Value:'0',  Expression:'\|ds:traffic_in\|,\|query_ifHighSpeed\|,/,0.0008,*',  Processed:'0,0,/,0.0008,*'
2021-03-19 21:10:03 - THOLD ERROR: RPN value: v2 "" is Not valid for operator "*". Stack:"0.0008"
2021-03-19 21:10:03 - THOLD ERROR: RPN Expression is invalid! THold:'MANCINI-SW1 - Traffic - Stack
```
This is a 24 port switch with a stack port only the stack port is reporting the issue While looking since the stackport is down right now it's getting a NaN value so I bet that's whats breaking the RPN

**Comment by ikorzha** [comment]
Sean I agree with your assessment.
I checked a few interfaces randomly from the log that error-ed out.
All of them have 0 bits data in and out, hence the error.
It appears to be it might be an easy fix to handle such condition…

An example of the interface and error below:
![image](https://user-images.githubusercontent.com/11211789/111856199-7f607d00-88ff-11eb-8e8e-8dc07be34e61.png)
![image](https://user-images.githubusercontent.com/11211789/111856181-648e0880-88ff-11eb-87da-b5d042a27d67.png)

**Comment by bernisys** [comment]
Maybe it's worth adding some input sanitization steps prior to actually handling the RPN.
If an interface doesn't receive any valid data, we should have the log already in the polling-section, so we don't need additional logs in the thold-section.

I have a quite similar error showing up in my logs, but for me it is even worse, because the data source information is not resolved properly. This adds the problem that i cannot even see which threshold it refers to. So multiple bugs (or past-echoes of them) are hitting us at the same time in our environment at the moment.

Gory details:
2021-03-25 02:57:12 - THOLD ERROR: RPN Expression is invalid! THold:'|data_source_description|', Value:'314068754.33444', Expression:'|ds:traffic_out|,|query_ifHighSpeed|,1000000,*,/,800,*', Processed:'314068754.33444,0,1000000,*,/,800,*'

I assume that this is pointing to an interface which (inside the DB) "forgot" its "ifHighSpeed" value from the host_snmp_cache table. This was related to a bug in the past. We're currently trying to resolve those issues by re-scanning the devices, but this is a lot of manual work, because it creates duplicate graphs which need to be merged and the old counterparts removed again.

What would really help in this case: Adding the thold_id to the log line, like cacti does already in some places for host, DS and graph IDs. In fact, i would wish generally for a more consistent log output, containing such information for each line.

Maybe i should open a new ticket with this more generic issue of adding more log-verbosity?

**Comment by bernisys** [comment]
@ikorzha Do you see proper ifHighSpeed values coming from the device via SNMP?
Check also the host_snmp_cache table for entries coming from the device, you probably see several zeros there.
That is most likely the actual source of the problem, as it produces a division by zero error, but the error message itself is not very verbose. We're seeing the same problem here a lot.

Let's take apart the error mesasge:
```
Value:'0'  <-- this is the _actual value_ that causes the issue, not the position of the placeholder
Expression:'\|ds:traffic_in\|,\|query_ifHighSpeed\|,/,0.0008,*',
Processed:'0,0,/,0.0008,*'  <-- so it is actually trying to calculate  0 / 0 * 0.0008
```
|ds:traffic_in| = 0  (which is okay, because we don't divide by that)
|query_ifHighSpeed| = 0  (this is the problematic "0" value which is reported)

So the real problem here is the division by the second parameter which is zero, and this is mathematically not defined, hence the errors you see.

**Comment by TheWitness** [comment]
Wow, best description of the problem I've seen.

**Comment by TheWitness** [comment]
What we should be doing is using the 'default' ifHighSpeed during replacement.  Let me look at that.  Otherwise, the error is correct.  Let me look at a carrying forward the enhancement that we've done for the ifSpeed/ifHighSpeed hack.

**Comment by TheWitness** [comment]
Okay, I changed the order of evaluation.  This should fix things up.

**Comment by TheWitness** [comment]
Basically, in your case, the value for ifHighSpeed was 0, for the core string replacement was a valid value, so to fix this, I moved the evaluation up to cure that problem.  So, this is an enhancement that I believe was previously done, but done incorrectly.

**Comment by ikorzha** [comment]
TheWitness thank you for addressing log errors and my apologies for original title. They are now been resolved in the log.
Unfortunately it is not the end of the problem as RPN expression doesn't produce usable calculation results.
For the start: I am using the following RPN formula to calculate interface % usage: |ds:traffic_in|,|query_ifHighSpeed|,/,0.0008,*
In thold template "Alert - High" defined as 85 (which would be 85%..
template below:
![image](https://user-images.githubusercontent.com/11211789/114279427-a7289980-9a02-11eb-8573-5bb003f3df31.png)
But in thold Interface high shows as 680 when it should be 85.. 85x8=680 (thold high shoould not be mutiplied x8).. Sometimes it is negative 680, however interface traffic use can never be a negative % number:
![image](https://user-images.githubusercontent.com/11211789/114279528-261dd200-9a03-11eb-932e-f1ca087521f6.png)
or
![image](https://user-images.githubusercontent.com/11211789/114279562-49488180-9a03-11eb-957d-6bd7c033b1b2.png)

I do not think calculations are correct either.
Can you please be kind enough to fix this issue.
I can open a separate bug id if required.

**Comment by TheWitness** [comment]
If you can figure it out, a pull request would be welcomed.

**Comment by ikorzha** [comment]
TheWitness unfortunately I am pretty "dumbass" when it comes to coding. I wouldn't be able to figure it out in million years.
I am going to close this issue as resolved and open a new bug report pertaining to incorrect max value being reported and measured against in thold as applicable to RPN functions..
Hopefully someone with greater understanding can chip in..

**Comment by bernisys** [comment]
For completeness, to be able to follow up when someone stumbles on this thread:
The remaining topic is discussed in issue #505

**Comment by bernisys** [comment]
@TheWitness I Just found some time, followed the thread completely and saw this comment of yours:

> What we should be doing is using the 'default' ifHighSpeed during replacement. Let me look at that. Otherwise, the error is correct. Let me look at a carrying forward the enhancement that we've done for the ifSpeed/ifHighSpeed hack.

I'm unsure if that is really a wise decision. I find such defaults can be dangerous.

If the speed value of an interface cannot be determined, and it is used in RPN expressions, i'd rather see it fail than having a totally wrong number just by taking some defaults which are not guaranteed  and this **will** lead to wrong alerting when using the thresholds module.
Imagine you set the default to 1GBit but you have devices with 10..100 MBit interfaces, the value will never even reach 10% ..
Otherwise, if you set the default too low, the interface will constantly be over the threshold.

If you assume and use defaults, you should rather:
  - at least have some warnings in the logs, when such defaults are used in calculations instead of queried values
    (means that the logs would be still there, but much more useful than this sometimes confusing RPN error)
  - have these defaults configurable at least per device (still dangerous, but less than a global default)
  - add a possibility to manually change the value for each interface individually

p.S. 
> Wow, best description of the problem I've seen.

thanks, i'm always trying to be as verbose & precise as possible :)
you might see my other posts are following a similar pattern .. better to write a bit more side info, so that others can understand the thoughts. I hope i don't over do it :D
