### ISSUE TITLE
A DB Cell Failed!, Error: Illegal mix of collations

### ISSUE THREAD

**Issue by ISekan** [Cacti/plugin_thold#637]
Cacti 1.2.25
MariaDB 11.2.1
thold 1.5.2

I got some errors
![image](https://github.com/Cacti/plugin_thold/assets/17400240/9e8fc065-b18d-4c44-82e3-00588810b935)

**Comment by TheWitness** [comment]
Please run the convert_tables.php script to correct this issue or since your are at utf8, just write a script to convert the collation/charset's of all the tables to utf8 instead of utf8mb4 (the default).

You can run the following to see which tables are in the wrong character set;

```sql
SELECT table_name, table_collation, engine FROM information_schema.tables WHERE table_schema='cacti'
```

The convert_tables.php script does utf8mb4 by default, if you want utf8, write a script to run this command for each table:

```sql
use cacti;
ALTER TABLE tbl_name CONVERT TO CHARACTER SET utf8;
```
