### ISSUE TITLE
Different dimension - MegaBytes instead of Megabits

### ISSUE THREAD

**Issue by click0** [Cacti/plugin_thold#78]
Different dimension - MegaBytes instead of Megabits
![capture_05062017_181611](https://cloud.githubusercontent.com/assets/396824/25774067/982960ea-3291-11e7-96c0-031fcb983a78.jpg)

Cacti 1.1.6 (devel branch) and plugin_thold 1.0.3

**Comment by cigamit** [comment]
This is due to the cdef, the way thold is working today is looking at the raw value and not the cdef manipulated value (which multiplies by 8) for the bit's/second.  So, the units will be off by roughly an order of magnitude.  The value should be correct if you create a bytes/second chart and apply a thold to it.

**Comment by TheWitness** [comment]
This issue is resolved now.
